import { LanguageCode } from './common'

export interface Video {
  id: string
  channel: {
    id: string
    name: string
    thumbnail: string
  }
  state: number
  metadata: {
    title: string
    description: string
    type: number
    url: string
    duraton: number
    upload_date: string
    deleted: boolean
  }
  transcription: number
  translations: Record<LanguageCode, number>
}

export interface Paginated<T> {
  page: number
  per_page: number
  total: number
  data: T
}

export const enum OverallState {
  NoWork = -1,
  Waiting = 0,
  Working = 1,
  Done = 100,
  NeedReUpload = 105,
  UploadDone = 110,
}

export const enum SpecificState {
  Waiting = 0,
  Translating = 1,
  Captioning = 2,
  ExtraCaptioning = 3,
  Reworking = 10,
  Reviewing = 50,
  Done = 100,
}

export const OverallStateNames: Record<OverallState, string> = {
  [OverallState.NoWork]: '작업 안함',
  [OverallState.Waiting]: '작업 대기 중',
  [OverallState.Working]: '작업 중',
  [OverallState.Done]: '업로드 대기 중',
  [OverallState.NeedReUpload]: '재 업로드 대기 중',
  [OverallState.UploadDone]: '업로드 완료',
}

export const LanguageNames: Record<LanguageCode, string> = {
  aa: "아파르어",
  ab: "압하스어",
  ae: "아베스타어",
  af: "아프리칸스어",
  ak: "아칸어",
  am: "암하라어",
  an: "아르곤어",
  ar: "아랍어",
  as: "아샘어",
  av: "아바릭어",
  ay: "아이마어",
  az: "아제르바이잔어",
  ba: "바슈키르어",
  be: "벨라루스어",
  bg: "불가리아어",
  bh: "비하리어",
  bi: "비슬라마어",
  bm: "밤바라어",
  bn: "벵골어",
  bo: "티베트어",
  br: "브르타뉴어",
  bs: "보스니아어",
  ca: "카탈루냐어",
  ce: "체첸어",
  ch: "차모로어",
  co: "코르시카어",
  cr: "크리어",
  cs: "체코어",
  cu: "교회 슬라브어",
  cv: "카투마어",
  cy: "웨일스어",
  da: "덴마크어",
  de: "독일어",
  dv: "디베히어",
  dz: "종카어",
  ee: "에웨어",
  el: "현대 그리스어",
  en: "영어",
  eo: "에스페란토",
  es: "스페인어",
  et: "에스토니아어",
  eu: "바스크어",
  fa: "페르시아어",
  ff: "풀라어",
  fi: "핀란드어",
  fj: "피지어",
  fo: "페로어",
  fr: "프랑스어",
  fy: "프리지아어",
  ga: "아일랜드어",
  gd: "스코틀랜드 게일어",
  gl: "갈리시아어",
  gn: "과라니어",
  gu: "구자라티어",
  gv: "맨어",
  ha: "하우사어",
  he: "히브리어",
  hi: "힌디어",
  ho: "히로무어",
  hr: "크로아티아어",
  ht: "아이티크리올어",
  hu: "헝가리어",
  hy: "아르메니아어",
  hz: "헤레로어",
  ia: "인터링구아",
  id: "인도네시아어",
  ie: "인터링구어",
  ig: "이그보어",
  ii: "쓰촨 이어",
  ik: "이누피아크어",
  io: "이도",
  is: "아이슬란드어",
  it: "이탈리아어",
  iu: "이누이트어",
  ja: "일본어",
  jv: "자바어",
  ka: "그루지야어",
  kg: "콩고어",
  ki: "키쿠유어",
  kj: "콰냐마어",
  kk: "카자흐어",
  kl: "그린란드어",
  km: "크메르어 ",
  kn: "칸나다어",
  ko: "한국어",
  kr: "카누리어",
  ks: "카슈미르어",
  ku: "쿠르드어",
  kv: "페름어",
  kw: "콘월어",
  ky: "키르기스어",
  la: "라틴어",
  lb: "룩셈부르크어",
  lg: "간다어",
  li: "림뷔르흐어",
  ln: "링갈라어",
  lo: "라오어",
  lt: "리투아니아어",
  lu: "루바카탕가어",
  lv: "라트비아어",
  mg: "마다가스카르어",
  mh: "마셜어",
  mi: "마오리어",
  mk: "마케도니아어",
  ml: "말라얄람어",
  mn: "몽골어",
  mr: "마라타어",
  ms: "말레이어",
  mt: "몰타어",
  my: "미얀마어",
  na: "나우루어",
  nb: "노르웨이어",
  nd: "은데벨레어",
  ne: "네팔어",
  ng: "느동가어",
  nl: "네덜란드어",
  nn: "뉘노르스크어",
  no: "노르웨이어",
  nr: "남은데벨레어",
  nv: "나바호어",
  ny: "체와어",
  oc: "프로방스어",
  oj: "오지브와어",
  om: "오로모어",
  or: "오리야어",
  os: "오세트어",
  pa: "펀자브어",
  pi: "팔리어",
  pl: "폴란드어",
  ps: "파슈툰어",
  pt: "포르투갈어",
  qu: "케추아어",
  rm: "레토로망스어",
  rn: "룬디어",
  ro: "루마니아어",
  ru: "러시아어",
  rw: "르완다어",
  sa: "산스크리트어",
  sc: "사르데냐어",
  sd: "신드어",
  se: "북사미어",
  sg: "상고어",
  si: "싱할라어",
  sk: "슬로바키아어",
  sl: "슬로베니아어",
  sm: "사모아어",
  sn: "쇼나어",
  so: "소말리어",
  sq: "알바니아어",
  sr: "세르비아어",
  ss: "스와티어",
  st: "남소토어",
  su: "순다어",
  sv: "스웨덴어",
  sw: "스와힐리어",
  ta: "타밀어",
  te: "텔루구어",
  tg: "타지크어",
  th: "태국어",
  ti: "티그리냐어",
  tk: "투르크멘어",
  tl: "타갈로그",
  tn: "츠와나어",
  to: "통가어",
  tr: "터키어",
  ts: "총가어",
  tt: "타타르어",
  tw: "트위어",
  ty: "타이티어",
  ug: "위구르어",
  uk: "우크라이나어",
  ur: "우르두어",
  uz: "우즈베크어",
  ve: "벤다어",
  vi: "베트남어",
  vo: "볼라퓌크",
  wa: "왈론어",
  wo: "월로프어",
  xh: "코사어",
  yi: "이디시어",
  yo: "요루바어",
  za: "주앙어",
  zh: "중국어",
  zu: "줄주어",
};